name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
        id: go
      - uses: actions/checkout@v4
      - name: go get
        run: go get -v -t -d ./...
      - name: go build
        run: go build -v .
      - name: go test
        run: go test ./... -cover -race
      - name: go vet
        run: go vet ./...
